----------------
-- Delete tables
DROP TABLE ORDERS;
DROP TABLE PETS;
DROP TABLE CUSTOMERS;
DROP TABLE SERVICES;
DROP TABLE EMPLOYEES;
DROP TABLE ADMINS;
-- End of delete tables


-------------------
-- Delete sequences
DROP SEQUENCE SEQ_CUSTOMERS_ID;
DROP SEQUENCE SEQ_PETS_ID;
DROP SEQUENCE SEQ_SERVICES_ID;
DROP SEQUENCE SEQ_ORDERS_ID;
DROP SEQUENCE SEQ_ADMINS_ID;
DROP SEQUENCE SEQ_EMPLOYEES_ID;
-- End of delete sequences
