----------------
-- Delete tables
DROP TABLE ORDERS;
DROP TABLE PETS;
DROP TABLE CUSTOMERS;
DROP TABLE SERVICES;
DROP TABLE ADMINS;
DROP TABLE EMPLOYEES;
-- End of delete tables


-------------------
-- Delete sequences
DROP SEQUENCE SEQ_CUSTOMERS_ID;
DROP SEQUENCE SEQ_PETS_ID;
DROP SEQUENCE SEQ_SERVICES_ID;
DROP SEQUENCE SEQ_ORDERS_ID;
DROP SEQUENCE SEQ_ADMIN_ID;
DROP SEQUENCE SEQ_EMPLOYEE_ID;
-- End of delete sequences
